# Generated by Django 4.2.4 on 2023-09-02 03:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('vencimiento', models.DateField()),
                ('estados', models.CharField(choices=[('iniciado', 'iniciado'), ('casi-casi', 'casi-casi'), ('meta cumplida', 'meta cumplida')], default='iniciado', max_length=20)),
                ('etiqueta_tarea', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tareas.etiqueta')),
                ('identificador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
